# Generated by Django 3.0.4 on 2021-11-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('tweet', models.TextField(max_length=255, verbose_name='tweet')),
                ('create_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
