# Generated by Django 3.0.4 on 2021-11-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.TimeField(auto_now_add=True, verbose_name='作成日'),
        ),
    ]
